version: "3.9"

services:  
  backend:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
        - .:/workspace/
        - ~/.ssh:/home/vscode/.ssh:ro
        - ~/.aws:/home/vscode/.aws:ro 
    tty: true